[tools]
gitleaks = "8.22.1"
go = "1.23.4"
golangci-lint = "1.63.4"
hadolint = "2.12.0"
k6 = "0.55.2"
task = "3.40.1"
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "latest"

[env]
CONFIG_PATH = "{{config_root}}/config/config.yaml"
