[tools]
gitleaks = "8.24.0"
go = "1.24.0"
golangci-lint = "1.64.5"
hadolint = "2.12.0"
k6 = "0.57.0"
task = "3.41.0"
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "latest"

[env]
CONFIG_PATH = "{{config_root}}/config/config.yaml"
