branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: refactor
          release: patch
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - message: "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
  - "@semantic-release/github"
