branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: refactor
          release: patch
        - type: chore
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Feature
          - type: fix
            section: Fix
          - type: chore
            section: Chore
          - type: docs
            section: Documentation
          - type: refactor
            section: Refactor
          - type: perf
            section: Performance
          - type: test
            section: Test
          - type: ci
            section: CI
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - message: "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
  - "@semantic-release/github"
