version: "3"

services:
  prometheus:
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - ./grafana.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 9000:3000
