version: "3"

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=template
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    command: mongod --setParameter notablescan=1
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - 6379:6379
