version: "3"

services:
  prometheus:
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - ./grafana.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 9000:3000

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    ports:
      - 16686:16686 # serve frontend
      - 14268:14268 # accep jaeger.thrift directly from clients
      - 4317:4317 # accep OpenTelemetry Protocol (OTLP) over gRPC
    extra_hosts:
      - "host.lima.internal:host-gateway"
