env: development

logger:
  level: debug

http:
  port: 3000
  limiter:
    requests: 1000
    expiration: 1s

metrics:
  addr: localhost:9091

tracing:
  addr: localhost:4317
  secure: false
  timeout: 1s
  sample_rate: 1.0

casdoor:
  endpoint: http://localhost:8000
  client_id: a569a49be76d0d95fa5b
  client_secret: 5c1c81b9c8706156bcb57d712297c34b6d899d50
  certificate: "-----BEGIN CERTIFICATE-----\nMIIE3TCCAsWgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCgxDjAMBgNVBAoTBWFk\nbWluMRYwFAYDVQQDEw1jZXJ0LWJ1aWx0LWluMB4XDTI0MTIxODAzMzYxOVoXDTQ0\nMTIxODAzMzYxOVowKDEOMAwGA1UEChMFYWRtaW4xFjAUBgNVBAMTDWNlcnQtYnVp\nbHQtaW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDXSKxnq1zf3lW/\nuRw35hH0e2mjsLH47zZA8LPAghK9AhnVLrS0O1JblPqrOQgOf9Ox3oDlCoz1WW3k\n+Qnq+WJfiex+whcAutSPwFgW4vbIZY6WpVkUFsmov0rmBv4QbHSKnZOuYuJ6RCEw\nbJYqlVf40c5e1uEDQEDLRpwmJMfh/Kgs1yTVFEReLcTafn2aDQn3DwFSEGZEhaj6\n1PYfLdLOTHy7MlW77sm0nS4kkabgXLLAHbq5IS0vlehzJPUxnWFEVsrbEK4crasu\ns/4epXVuBWOGzmDBHXkhTrenW/GWRMj4YIcfnGiC1Uz+rOaPMcHBIU/GAaNo5ZaU\n5WBLPPIHSCyhMHJWeWuVGcYG2LiGsT5M6AsSDWA8r7vnynOTvoEEVC62yOqkjaF+\nnjX5Z7z4B9UrcOeYQMshXYqc74y0KFBzi1DK9BIXc5q5faOVaZeXkWyD27PxV/u5\n/AjuqWgWjdgNghSaW+QMgtSb+BlaJjCyYvM2ND+i/Ere6nInEFYXjsvR9Xfejaow\nR2l3dy2Hq0nDwQZWwR/sebsNZI+TXC3kWJikJLLt9p3f27C8MjyYsFfjHRJTxFs8\nVnUNAuXoneUHVuzdZ1E/UesKUIddqwIxMuQU0eqj53tATFrM8OpZWI/amfz17p+1\nhg612aIR1seQXGVP1Idjdb7hpEWDvwIDAQABoxAwDjAMBgNVHRMBAf8EAjAAMA0G\nCSqGSIb3DQEBCwUAA4ICAQBPMbZo0Ln3QofG09L9mqrNZMLpQHJPXGcyB89FL5Xc\nTsrUoaKKOZzd4vG9XQ+Tk0dnWxAs/M5PXVqDKTcgcmcf3VWxla0HDpKp3RCkBfLQ\nN49codLpf1pVJ77lkwnrtBspBIcSPhyT/r8Ak1FEs35YzS3rPU5hl/BVRD8bSHyn\n7a0qDmaBRNA53r7hhmwhSQX7db6+NplANAL8QEOct+F+eR+BtuRsit2+VTNnTOj4\n18A4tlCAzHrOaT/c4iumuiGctgyw/sGOAQGcwgBI9OTN1IWRzSQOtCXngc85Kk5V\nD452U/8zSFRB2nGo6MjQpTn6VvsOz7DOL0cDdu0t6fN26g8dyL6cTD3AY71h7t05\n+6gr8hTIqWkeoHTR4DPXnbJ5FnHPqi+Ujca4zEQ82lMqwlmYlaiJd+Rc4NOZfITO\nIecBChC67bklFHNxQzz7EahG0BMJyxjE+Soo8aglw7o+jaWVPqQXLl11nNbyohjo\niwqjmwfEov9BItYASkJfQnysTemyi1isL+SsbeCbwiotQ1Jxrt2CPtXvbkTYEpg6\nt/xhs5vw7fxMLVgyapVZS+Oe9anncZR2w/sdndX0zgVx0hwRFEZl6nQNdgi7M2RA\ny2ulVQmNFfLJCK/meHBQzPFwQ1mjychK5+RIPe0//xlEfPhZuMg9o2Q+pC6B6Prd\nEQ==\n-----END CERTIFICATE-----\n"
  organization_name: built-in
  application_name: app-built-in

feature_flags:
  polling_interval: 15s
  flags:
    cool-feature:
      variations:
        on: "on"
        off: "off"
      defaultRule:
        percentage:
          on: 50
          off: 50

postgres:
  uri: postgres://postgres:postgres@localhost:5432/template?sslmode=disable

mongo:
  uri: mongodb://localhost:27017

redis:
  addr: localhost:6379
